name: JiwuChat CI
 
on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    workflow_dispatch:
 
jobs:
    release:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                # 选择编译平台
                platform: [windows-latest, macos-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
 
            - name: Install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-20.04'
              # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev
 
            - name: Rust setup
              uses: dtolnay/rust-toolchain@stable
 
            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: './src-tauri -> target'
 
            - name: Sync node version and insatll nodejs
              uses: actions/setup-node@v3
              with:
                  node-version: 20
 
            # 使用 pnpm 作为包管理器
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              id: pnpm-install
              with:
                  version: 8
                  run_install: false
 
            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
 
            - uses: actions/cache@v4
              name: Setup pnpm cache
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-
 
            - name: Install app dependencies and build it
              run: pnpm i && pnpm build:nuxt
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
            
            - name: Read Release Body Content
              id: read_release_body
              uses: actions/github-script@v7
              with:
                script: |
                  const fs = require('fs').promises;
                  try {
                    const path = `.github/workflows/${{github.ref_name}}.md`;
                    const content = await fs.readFile(path, 'utf8');
                    core.exportVariable('RELEASE_BODY_CONTENT', content);
                  } catch (error) {
                    core.setFailed(`Failed to read file: ${error}`);
                  }

            - name: Create Release
              uses: tauri-apps/tauri-action@v0.5.6
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
              with:
                tagName: ${{ github.ref_name }}
                releaseName: 'v__VERSION__'
                # 正确引用步骤输出的变量
                # releaseBody: $#{{ steps.get_release_body.outputs.releaseBody }}
                # releaseBody: "**Full Changelog**: https://github.com/KiWi233333/jiwu-mall-chat-tauri/blob/main/.github/releasemd/${{ github.ref_name }}.md"
                releaseBody: ${{ env.RELEASE_BODY_CONTENT }}
                releaseDraft: false
                prerelease: false
